title: "梦与远方"
description: "梦境与游记"
url: "https://zhucebuniao.github.io"
baseurl: ""
lang: "zh-CN"
author: "zhucebuniao"
future: true

markdown: kramdown

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
