# Site Configuration
title: "像素世界"
description: "一个复古8位风格的GitHub Pages网站，具有像素艺术风格"
url: "https://zhucebuniao.github.io"
baseurl: ""
lang: "zh-CN"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  games:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/