# Site Configuration
title: "极简博客"
description: "一个极简风格的个人博客，专注于内容和可读性"
url: "https://zhucebuniao.github.io"
baseurl: ""
lang: "zh-CN"
author: "博客作者"

# Build settings
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
  sass_dir: _sass

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Collections
collections:
  games:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "像素创造者"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Blog settings
excerpt_separator: "<!-- more -->"
show_excerpts: true

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/